import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { canonicalJson, compareQualityArtifacts, createReviewSummary, createVisualReviewManifest, evaluateQuality, getQualityMetric, sha256Canonical, sha256Text, verifyQualityArtifact, type QualityArtifact, type QualityEvaluationInput, type QualityMetricName } from "../src/quality.ts";
const digest=(value:string)=>sha256Text(value);
function input(): QualityEvaluationInput { const mask0=[1,0,0,1,0,0];const mask1=[0,1,0,0,1,0];return {schemaVersion:1,kind:"web-ar-occlusion-quality-input",provenance:{evaluatedAt:"2026-01-02T03:04:05.000Z",sourceKind:"synthetic-fixture",sourceId:"seeded-correctness-fixture",sourceDigest:digest("source"),implementationId:"implementation-a",implementationDigest:digest("implementation-a"),configDigest:digest("config"),evaluatorVersion:"quality-v1"},depthScale:"metric",frames:[{id:"f0",timestampMs:0,width:3,height:2,predictedMask:[...mask0],referenceMask:[...mask0],predictedDepth:[1,2,3,4,5,6],referenceDepth:[1,2,3,4,5,6],confidence:[1,1,1,1,1,1],renderedAlpha:[...mask0],referenceRenderedAlpha:[...mask0]},{id:"f1",timestampMs:20,width:3,height:2,predictedMask:[...mask1],referenceMask:[...mask1],predictedDepth:[2,3,4,5,6,7],referenceDepth:[2,3,4,5,6,7],confidence:[1,1,1,1,1,1],renderedAlpha:[...mask1],referenceRenderedAlpha:[...mask1]}],reviewItems:[{id:"still-1",kind:"image",uri:"fixtures/still-1.png",sha256:digest("still")} ]}; }
function metric(artifact:QualityArtifact,name:QualityMetricName):number { const result=getQualityMetric(artifact,name);assert.equal(result.status,"known");return result.value!; }
function redigest(artifact:QualityArtifact):QualityArtifact { const {digest:_old,...unsigned}=artifact;return {...unsigned,digest:sha256Canonical(unsigned)}; }
test("canonical JSON and SHA-256 are stable, ordered, and strict",()=>{assert.equal(canonicalJson({z:1,a:{d:2,b:1}}),'{"a":{"b":1,"d":2},"z":1}');assert.equal(sha256Canonical({b:2,a:1}),sha256Canonical({a:1,b:2}));assert.throws(()=>canonicalJson({bad:Number.NaN}));assert.throws(()=>canonicalJson({bad:undefined}));});
test("versioned artifact contract and provenance verify",()=>{const artifact=evaluateQuality(input());assert.equal(artifact.schemaVersion,1);assert.equal(artifact.claims.benchmark,false);assert.equal(artifact.metrics.length,18);assert.deepEqual(verifyQualityArtifact(artifact),{valid:true,errors:[]});});
test("correctness fixture produces exact depth, mask, boundary, thin, and temporal metrics",()=>{const artifact=evaluateQuality(input());for(const name of ["depth.mae.m","depth.rmse.m","depth.abs-relative","depth.si-log-rmse","confidence.calibration-mae","temporal.jitter","temporal.delay-ms","temporal.ghost-rate","temporal.over-smoothing-rate","rendered.disagreement-rate","safety.foreground-leak-rate"] as QualityMetricName[])assert.equal(metric(artifact,name),0);for(const name of ["mask.iou","mask.precision","mask.recall","boundary.f1","thin.recall","confidence.mean","confidence.coverage"] as QualityMetricName[])assert.equal(metric(artifact,name),1);});
test("depth defect is detected by metric and relative-depth metrics",()=>{const fixture=input();fixture.frames[0]!.predictedDepth![0]=2;const artifact=evaluateQuality(fixture);assert.ok(metric(artifact,"depth.mae.m")>0);assert.ok(metric(artifact,"depth.rmse.m")>0);assert.ok(metric(artifact,"depth.abs-relative")>0);assert.ok(metric(artifact,"depth.si-log-rmse")>0);});
test("confidence defects affect mean, coverage, and calibration",()=>{const fixture=input();fixture.frames[0]!.confidence=[0,0,null,null,null,null];delete fixture.frames[1]!.confidence;const artifact=evaluateQuality(fixture);assert.equal(metric(artifact,"confidence.mean"),0);assert.equal(metric(artifact,"confidence.coverage"),2/12);assert.equal(metric(artifact,"confidence.calibration-mae"),1);});
test("mask, boundary, and thin-structure defects are measured",()=>{const perfect=evaluateQuality(input());const fixture=input();fixture.frames[1]!.predictedMask=[0,0,0,0,0,0];const artifact=evaluateQuality(fixture);assert.ok(metric(artifact,"mask.iou")<metric(perfect,"mask.iou"));assert.ok(metric(artifact,"boundary.f1")<metric(perfect,"boundary.f1"));assert.ok(metric(artifact,"thin.recall")<metric(perfect,"thin.recall"));});
test("temporal delay, ghosting, and over-smoothing fail explicitly",()=>{const fixture=input();fixture.frames[1]!.predictedMask=[...fixture.frames[0]!.predictedMask];const artifact=evaluateQuality(fixture);assert.ok(metric(artifact,"temporal.ghost-rate")>0);assert.ok(metric(artifact,"temporal.over-smoothing-rate")>0);const delay=getQualityMetric(artifact,"temporal.delay-ms");assert.equal(delay.status,"unknown");assert.equal(delay.reason,"unresolved-reference-transitions");});
test("rendered disagreement and foreground safety leakage are measured",()=>{const fixture=input();fixture.frames[1]!.predictedMask=[0,0,0,0,0,0];fixture.frames[1]!.renderedAlpha=[1,1,1,1,1,1];const artifact=evaluateQuality(fixture);assert.ok(metric(artifact,"rendered.disagreement-rate")>0);assert.ok(metric(artifact,"safety.foreground-leak-rate")>0);});
test("missing metric scale and observations remain explicit rather than zero-filled",()=>{const fixture=input();fixture.depthScale="relative";delete fixture.frames[0]!.confidence;delete fixture.frames[1]!.confidence;const artifact=evaluateQuality(fixture);assert.equal(getQualityMetric(artifact,"depth.mae.m").status,"missing");assert.equal(getQualityMetric(artifact,"depth.abs-relative").status,"known");assert.equal(getQualityMetric(artifact,"confidence.mean").status,"missing");assert.equal(metric(artifact,"confidence.coverage"),0);});
test("multi-objective comparison reports better, worse, equivalent, and tradeoff",()=>{const perfect=evaluateQuality(input());const damagedInput=input();damagedInput.frames[0]!.predictedDepth![0]=2;damagedInput.frames[0]!.predictedMask[0]=0;const damaged=evaluateQuality(damagedInput);assert.equal(compareQualityArtifacts(damaged,perfect).verdict,"better");assert.equal(compareQualityArtifacts(perfect,damaged).verdict,"worse");assert.equal(compareQualityArtifacts(perfect,perfect).verdict,"equivalent");const candidate=structuredClone(perfect);getQualityMetric(candidate,"depth.rmse.m").value=0;getQualityMetric(candidate,"mask.iou").value=0.5;const baseline=structuredClone(perfect);getQualityMetric(baseline,"depth.rmse.m").value=1;getQualityMetric(baseline,"mask.iou").value=0.75;assert.equal(compareQualityArtifacts(redigest(baseline),redigest(candidate),[{metric:"depth.rmse.m",direction:"min"},{metric:"mask.iou",direction:"max"}]).verdict,"tradeoff");});
test("comparison fails closed for tampering, provenance mismatch, and unknown objectives",()=>{const baseline=evaluateQuality(input());const tampered=structuredClone(baseline);getQualityMetric(tampered,"mask.iou").value=0;assert.equal(compareQualityArtifacts(baseline,tampered).verdict,"incomparable");const different=structuredClone(baseline);different.provenance.sourceDigest=digest("different");assert.equal(compareQualityArtifacts(baseline,redigest(different)).verdict,"incomparable");const unknown=structuredClone(baseline);const item=getQualityMetric(unknown,"mask.iou");delete item.value;item.status="unknown";item.reason="review-unresolved";assert.equal(compareQualityArtifacts(baseline,redigest(unknown),[{metric:"mask.iou",direction:"max"}]).verdict,"incomparable");});
test("tampered artifact digest is rejected",()=>{const artifact=evaluateQuality(input());artifact.provenance.implementationId="changed";const result=verifyQualityArtifact(artifact);assert.equal(result.valid,false);assert.match(result.errors[0]!,/digest mismatch/);});
test("review-only summary is deterministic, bounded, and disclaims benchmark conclusions",()=>{const artifact=evaluateQuality(input());const first=createReviewSummary(artifact,180);const second=createReviewSummary(artifact,180);assert.deepEqual(first,second);assert.ok(first.text.length<=180);assert.equal(first.reviewOnly,true);assert.match(first.text,/REVIEW ONLY/);assert.match(first.text,/not a benchmark claim/);});
test("visual review manifest is digest-bound, bounded, local, and review-only",()=>{const artifact=evaluateQuality(input());const manifest=createVisualReviewManifest(artifact,1);assert.equal(manifest.artifactDigest,artifact.digest);assert.equal(manifest.items.length,1);assert.equal(manifest.reviewOnly,true);assert.equal(manifest.truncated,false);const unsafe=input();unsafe.reviewItems![0]!.uri="https://example.test/image.png";assert.throws(()=>evaluateQuality(unsafe),/repository-relative/);});
test("input validation rejects missing, invalid, and non-finite evidence",()=>{const malformed=input() as unknown as Record<string,unknown>;delete malformed.frames;assert.throws(()=>evaluateQuality(malformed));const nonfinite=input();nonfinite.frames[0]!.predictedMask[0]=Number.NaN;assert.throws(()=>evaluateQuality(nonfinite),/finite/);const unordered=input();unordered.frames[1]!.timestampMs=0;assert.throws(()=>evaluateQuality(unordered),/strictly increase/);});
test("evaluation is byte-for-byte repeatable",()=>{const first=evaluateQuality(input());const second=evaluateQuality(input());assert.equal(canonicalJson(first),canonicalJson(second));assert.equal(first.digest,second.digest);});
test("direct Node CLI supports evaluate, verify, compare, summary, and review-manifest",async()=>{const directory=await mkdtemp(join(tmpdir(),"quality-cli-"));try{const cli=fileURLToPath(new URL("../src/quality-cli.ts",import.meta.url));const inputPath=join(directory,"input.json");const artifactPath=join(directory,"artifact.json");await writeFile(inputPath,JSON.stringify(input()),"utf8");const run=(args:string[])=>spawnSync(process.execPath,[cli,...args],{encoding:"utf8"});const evaluated=run(["evaluate",inputPath]);assert.equal(evaluated.status,0,evaluated.stderr);const artifact=JSON.parse(evaluated.stdout);await writeFile(artifactPath,JSON.stringify(artifact),"utf8");for(const args of [["verify",artifactPath],["compare",artifactPath,artifactPath],["summary",artifactPath,"256"],["review-manifest",artifactPath,"1"]]){const result=run(args);assert.equal(result.status,0,result.stderr);assert.doesNotThrow(()=>JSON.parse(result.stdout));}assert.equal(JSON.parse(run(["compare",artifactPath,artifactPath]).stdout).verdict,"equivalent");}finally{await rm(directory,{recursive:true,force:true});}});
